---
title: "Logistic Regression Models in R"
output: 
  revealjs::revealjs_presentation:
    fig_width: 14 
    fig_height: 7
    self_contained: true
    theme: night
    highlight: zenburn
    css: slidesdjh.css
    center: false
    transition: slide
    reveal_options:
      controls: true
      progress: false
      width: 1080
      height: 540
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
options(width = 100)
library(tidyverse)
library(openintro)
theme_set(theme_bw())
```

# Pairs Today

- Please pair up (your choice).
    - At least one person in each pair needs to have a device that can use RStudio (installed or using rstudio.cloud). This person is the *Operator*.
    - Ideally, everyone has an RStudio-enabled device. If you don't, you can still take notes by keeping track of the code and trying it on your own later.
    
## Group Exercises

Do all the challenges.

```{r, eval = FALSE}
library(tidyverse)
library(openintro)

# Look at the duke_forest data frame
duke_forest
view(duke_forest)
```

---

```{r, eval = FALSE}
# Make a new data frame: 
#   Get rid of address, hoa, url columns
#   Add a factor column: 
#     New variable anypark: 0 if no spaces, 1 otherwise

homes <- duke_forest %>%
  select(-address, -hoa, -url) %>%
  mutate(anypark = factor(ifelse(parking == "0 spaces", 0, 1))) 
glimpse(homes)
view(homes)
```

---

```{r, eval = FALSE}
# Logistic regression

## Predict anypark from lot size

ggplot(homes, aes(x = lot, y = anypark)) +
  geom_boxplot()

model1 <- glm(anypark ~ lot, family = "binomial", data = homes)
summary(model1)

## predicted logit for 0.25 acre lot
-0.3922 + 1.1686*0.25
## predicted probability for 0.25 acre lot
exp(-0.3922 + 1.1686*0.25)/(1 + exp(-0.3922 + 1.1686*0.25))
```

---

```{r, eval = FALSE}
## Challenge: 
## 1. Compute the predicted logit for 0.5 acre lot.
## 2. Compute the predicted probability for 0.5 acre lot.
```

---

```{r, eval = FALSE}
## Check answers using the predict function.

# get predicted logit
predict(model1, data.frame(lot = c(0.25, 0.5)))

# get predicted probabilities
predict(model1, data.frame(lot = c(0.25, 0.5)), type = "response")
```

---

```{r, eval = FALSE}
## Challenge: 
## 1. Create a logistic regression model to predict anypark from 
##    price, lot, area, bath, bed (model2).
## 2. Try using step(model2) to eliminate variables. 
##    What happens? Why did it happen?
```

---

```{r, eval = FALSE}
# Drop rows containing missing values

homes_complete <- drop_na(homes)
model3 <- glm(anypark ~ price + lot + area + bath + bed, family = "binomial", data = homes_complete)
summary(model3)
step(model3)

ggplot(homes_complete, aes(x = price, y = anypark)) +
  geom_boxplot()
```

---

```{r, eval = FALSE}
## Challenge: 

# 1. Predict anypark from price (model4). Can use homes because we are not using lot.
# 2. Compare predicted probabilites for 400K vs 600K home.
```