---
title: "Bootstrapping and t-tests in R"
output: 
  revealjs::revealjs_presentation:
    fig_width: 14 
    fig_height: 7
    self_contained: true
    theme: night
    highlight: zenburn
    css: slidesdjh.css
    center: false
    transition: slide
    reveal_options:
      controls: true
      progress: false
      width: 1080
      height: 540
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
options(width = 100)
library(tidyverse)
library(openintro)
theme_set(theme_bw())
```

# Pairs Today

- Please pair up (your choice).
    - At least one person in each pair needs to have a device that can use RStudio (installed or using rstudio.cloud). This person is the *Operator*.
    - Ideally, everyone has an RStudio-enabled device. If you don't, you can still take notes by keeping track of the code and trying it on your own later.
    
## Group Exercises

Do all the challenges.

```{r, eval = FALSE}
library(tidyverse)
library(openintro)
glimpse(cherry)

## Load and inspect the data (graph)
glimpse(cherry)
ggplot(cherry, aes(x = height)) +
  geom_histogram()

## Challenge: Try a density plot instead of a histogram. Then try
# it for diam instead of height. How are each skewed? 

## Bootstrap samples
boots <- replicate(1000, mean(sample(cherry$height, 
                                     nrow(cherry), 
                                     replace = TRUE)))
sd(boots)
mean(boots) + c(-1,1)*2*sd(boots)
quantile(boots, c(0.025, 0.975))

## t test
t.test(cherry$height)

## Challenge (other variable)
# Do a t.test for the diam variable, and record a 95% confidence interval.
# Then do a bootstrap confidence interval for diam, and compare the results.
```


