---
title: "Review for Final Exam"
output: 
  revealjs::revealjs_presentation:
    fig_width: 14 
    fig_height: 7
    self_contained: true
    theme: night
    highlight: zenburn
    css: slidesdjh.css
    center: false
    transition: slide
    reveal_options:
      controls: true
      progress: false
      width: 1080
      height: 540
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
options(width = 100)
library(tidyverse)
library(openintro)
```

# General Advice 

- See the [study guide](https://westmont.instructure.com/courses/8503/files/635081). The Final Exam will be cumulative, with an emphasis on the material in Chapters 23–27. The study guide gives you some advice about which parts of Study Guides 1--4 to review.
- Review the slides and your class notes. 
    - As you review, follow along with the *textbook*.
    - As you review, keep a list of key terms and concepts.
    - Make sure you can answer all the *group activity questions*.
- Review your homework, keeping in mind that these have been graded very leniently.
- Do some of the *odd-numbered problems* in the textbook.
    - The answers to the odd-numbered questions are in the back of the book.
- Study the *Chapter Review* sections at the end of each chapter.

## Equations provided

- Linear regression
    - $\hat{y} = b_0 + b_1 x$
- Multiple linear regression
    - $\hat{y} = b_0 + b_1 x_{1} + b_2 x_{2} + \cdots + b_k x_{k}$
- Multiple logistic regression
    - $\log_e \left( \frac{\hat{p}}{1-\hat{p}} \right) = b_0 + b_1 x_{1} + b_2 x_{2} + \cdots + b_k x_{k}$
- Converting logit to probability
    - If $\log_e \left( \frac{\hat{p}}{1-\hat{p}} \right) = N$, then $\hat{p} = \frac{e^N}{1+e^N}$.
    
## Equations provided (continued)

- $T$-statistic for regression slope
    - $\displaystyle{T = \frac{r}{\sqrt{\frac{1-r^2}{n-2}}} = \frac{b_1 - 0}{SE_{b_1}}}$, $df = n-2$ 
- Confidence interval for slope
    - $b_1 \pm t^\star_{df} \times SE_{b_1}$, $df = n-2$ 

## Equations provided (continued)

- Generic SE confidence interval
    - $\mbox{point estimate} \pm 2 \cdot SE$
- $Z$-score    
    - $\displaystyle{Z = \frac{\text{point estimate} - \text{null value}}{SE}}$ 
- $Z$-interval
    - $\text{point estimate} \pm z^* \times SE$ 
- Standard error of $\hat{p}$
    - $\displaystyle{SE_{\hat{p}} \approx \sqrt{\frac{(\mbox{best guess of }p)(1 - \mbox{best guess of }p)}{n}}}$ 
    
## Equations provided (continued)

- One-sample t-test
    - $\displaystyle{T = \frac{\bar{x} - \text{null value}}{s/\sqrt{n}}}$, $df = n-1$ 
- One mean t-interval
    - $\displaystyle{\bar{x}  \pm  t^{\star}_{df} \times \frac{s}{\sqrt{n}}}$ 
- Two-sample t-test (independent means)
    - $\displaystyle{T = \frac{(\bar{x}_1 - \bar{x}_2) - 0}{\sqrt{s_1^2/n_1 + s_2^2/n_2}}}$, $df = \text{min}(n_1-1, n_2-1)$ 
    
## Equations provided (continued)

- Two-sample t-interval
    - $\displaystyle{\bar{x}_1 - \bar{x}_2 \pm t^\star_{df} \times \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}$ 
- Paired t-test
    - $\displaystyle{T = \frac{\bar{x}_\text{diff} - 0}{s_\text{diff}/\sqrt{n}}}$, $df = n-1$ 
- Paired t-interval
    - $\displaystyle{\bar{x}_\text{diff}  \pm  t^{\star}_{df} \times \frac{s_\text{diff}}{\sqrt{n}}}$ 
- ANOVA F-test
    - $\displaystyle{F = \frac{MSG}{MSE}}$, $df_1 = k-1$, $df_2 = n-k$

# Review Problems

## Questions on Homework Problems?

https://openintro-ims.netlify.app/

## Group Activity

- Chapter 24/ 13
- Chapter 25/ 7
- Chapter 26/ 6

## Requests?